Задание №1

In [ ]:
import numpy as np
def create_array(n):
    array_ = np.arange(n-1,-1,-1)
    print(array_)
create_array(10)

Задание №2

In [40]:
def create_diag_matrix(n):
    diag_matrx = np.diag(np.arange(n-1,-1,-1), k=0)
    print(diag_matrx)
    sum_=0
    for i in range(0,n-1):
        sum_+=diag_matrx[i][i]
    print("Сумма диагонали равна {}".format(sum_)) 
create_diag_matrix(15)

[[14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 13  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
Сумма диагонали равна 105


Задание №3

In [138]:
import pandas as pd
films = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
filtered_rating = ratings[ratings.rating == 5.0]
sorted_rating = filtered_rating.sort_values(by='movieId')
value_counts_ = sorted_rating['movieId'].value_counts()
most_rated_film_index = (value_counts_.index[0])
most_rated_film = films[films['movieId'] == most_rated_film_index]
print(most_rated_film)

     movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama


Задание №4

In [154]:
data = pd.read_csv('power.csv')
# print (data.head())
filtered_quanity = data[(data.quantity>0) & (data.year>2005) & (data.year<2010) & ((data.category==4) | (data.category==12) | (data.category==21)) & ((data.country=='Latvia') | (data.country=='Lithuania')|(data.country=='Estonia'))]
print("Общее потребление в соответствии с условиями из задания равно {}".format(int(filtered_quanity['quantity'].sum())))

Общее потребление в соответствии с условиями из задания равно 164555


Задание №5

In [161]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
print(linalg.solve(a, b))
np.allclose( np.dot(a, linalg.solve(a, b)), b )

[ 0.46666667  3.84444444 -5.55555556]


True